# Zookeeper configuration
dataDir=/var/lib/zookeeper/data
dataLogDir=/var/lib/zookeeper/logs
clientPort=2181
tickTime=2000
initLimit=5
syncLimit=2
maxClientCnxns=60
autopurge.snapRetainCount=3
autopurge.purgeInterval=1

