apiVersion: v1
kind: Namespace
metadata:
  name: gennet-system
  labels:
    name: gennet-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: gennet-workflows
  labels:
    name: gennet-workflows

